
package com.mycompany.arqueologia;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

public class ArqueologiaFrame extends javax.swing.JFrame {
    
    // Mensajes de error
    private static final String ERROR_MSG_INSERT = "Error al intentar dar de alta a esta persona.";
    private static final String ERROR_MSG_INSERT_INPUT = "No se admiten campos vacíos.";
    
    public ResultSet result;
    
    public ArqueologiaFrame() throws SQLException {
        Query.initQuery();
        initComponents();
        //label_error.setVisible(false);
        //Query.initQuery();
        result = Query.updateListaResultados(0);
        JTable_ObjetosGeneral.setModel(Query.resultToTable(result));
        result = Query.updateListaResultados(1);
        JTable_PersonasGeneral.setModel(Query.resultToTable(result));
        result = Query.updateListaResultados(2);
        JTable_SitiosGeneral.setModel(Query.resultToTable(result));
        result = Query.updateListaResultados(3);
        JTable_CuadriculasGeneral.setModel(Query.resultToTable(result));
        result = Query.updateListaResultados(4);
        JTable_CajasGeneral.setModel(Query.resultToTable(result));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPan_Header = new javax.swing.JPanel();
        Jlb_LogoBlanco = new javax.swing.JLabel();
        JPan_Contenedor = new javax.swing.JPanel();
        JPan_MenuPrincipal = new javax.swing.JPanel();
        JLb_ImagenIzquierda = new javax.swing.JLabel();
        JBtn_Altas = new javax.swing.JPanel();
        JLb_BtnAltas = new javax.swing.JLabel();
        JBtn_Listas = new javax.swing.JPanel();
        JLb_BtnListas = new javax.swing.JLabel();
        JBtn_Consultas = new javax.swing.JPanel();
        JLb_BtnConsultas = new javax.swing.JLabel();
        JLb_MarcaDeAgua = new javax.swing.JLabel();
        JPan_Altas = new javax.swing.JPanel();
        JBtn_AltaObjeto = new javax.swing.JPanel();
        JLb_AltaObjeto = new javax.swing.JLabel();
        JBtn_AltaPersona = new javax.swing.JPanel();
        JLb_AltaPersona = new javax.swing.JLabel();
        JBtn_AltaSitio = new javax.swing.JPanel();
        JLb_AltaSitio = new javax.swing.JLabel();
        JBtn_AltaCuadricula = new javax.swing.JPanel();
        JLb_AltaCuadricula = new javax.swing.JLabel();
        JBtn_AltaCaja = new javax.swing.JPanel();
        JLb_AltaCaja = new javax.swing.JLabel();
        JPan_AltaObjeto = new javax.swing.JPanel();
        JLb_AltaObj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTF_ACodObj = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTF_ANombObj = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTF_ATipExtObj = new javax.swing.JTextField();
        jSpin_AAlto = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpin_ALargo = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        JSpin_AEspesor = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpin_ACant = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        JPan_AltaPersona = new javax.swing.JPanel();
        JPan_AltaSitio = new javax.swing.JPanel();
        JPan_AltaCuadricula = new javax.swing.JPanel();
        JPan_AltaCaja = new javax.swing.JPanel();
        JPan_Listas = new javax.swing.JPanel();
        JTbpan_General = new javax.swing.JTabbedPane();
        JSP_ObjetosGeneral = new javax.swing.JScrollPane();
        JTable_ObjetosGeneral = new javax.swing.JTable();
        JSP_PersonasGeneral = new javax.swing.JScrollPane();
        JTable_PersonasGeneral = new javax.swing.JTable();
        JSP_SitiosGeneral = new javax.swing.JScrollPane();
        JTable_SitiosGeneral = new javax.swing.JTable();
        JSP_CuadriculasGeneral = new javax.swing.JScrollPane();
        JTable_CuadriculasGeneral = new javax.swing.JTable();
        JSP_CajasGeneral = new javax.swing.JScrollPane();
        JTable_CajasGeneral = new javax.swing.JTable();
        JPan_Consultas = new javax.swing.JPanel();
        JCB_Consultas = new javax.swing.JComboBox<>();
        JBtn_BuscarConsulta = new javax.swing.JPanel();
        JLb_BuscarConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPan_Header.setBackground(new java.awt.Color(27, 64, 142));
        JPan_Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPan_Header.setPreferredSize(new java.awt.Dimension(640, 100));

        Jlb_LogoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBlancoRedimensionado.png"))); // NOI18N
        Jlb_LogoBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jlb_LogoBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlb_LogoBlancoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlb_LogoBlancoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlb_LogoBlancoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPan_HeaderLayout = new javax.swing.GroupLayout(JPan_Header);
        JPan_Header.setLayout(JPan_HeaderLayout);
        JPan_HeaderLayout.setHorizontalGroup(
            JPan_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlb_LogoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JPan_HeaderLayout.setVerticalGroup(
            JPan_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlb_LogoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(JPan_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JPan_Contenedor.setLayout(new java.awt.CardLayout());

        JPan_MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        JPan_MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLb_ImagenIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImgAzul.png"))); // NOI18N
        JPan_MenuPrincipal.add(JLb_ImagenIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 420));

        JBtn_Altas.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_Altas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_Altas.setToolTipText("");
        JBtn_Altas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Altas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_AltasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltasMouseExited(evt);
            }
        });

        JLb_BtnAltas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_BtnAltas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnAltas.setText("ALTAS");
        JLb_BtnAltas.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltasLayout = new javax.swing.GroupLayout(JBtn_Altas);
        JBtn_Altas.setLayout(JBtn_AltasLayout);
        JBtn_AltasLayout.setHorizontalGroup(
            JBtn_AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltasLayout.setVerticalGroup(
            JBtn_AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_MenuPrincipal.add(JBtn_Altas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 50));

        JBtn_Listas.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_Listas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_Listas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_ListasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_ListasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_ListasMouseExited(evt);
            }
        });

        JLb_BtnListas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_BtnListas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnListas.setText("LISTAS PARA BAJAS Y EDICIONES");
        JLb_BtnListas.setFocusable(false);

        javax.swing.GroupLayout JBtn_ListasLayout = new javax.swing.GroupLayout(JBtn_Listas);
        JBtn_Listas.setLayout(JBtn_ListasLayout);
        JBtn_ListasLayout.setHorizontalGroup(
            JBtn_ListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnListas, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_ListasLayout.setVerticalGroup(
            JBtn_ListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnListas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_MenuPrincipal.add(JBtn_Listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 50));

        JBtn_Consultas.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_Consultas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_ConsultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_ConsultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_ConsultasMouseExited(evt);
            }
        });

        JLb_BtnConsultas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_BtnConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BtnConsultas.setText("CONSULTAS ESPECÍFICAS");
        JLb_BtnConsultas.setFocusable(false);

        javax.swing.GroupLayout JBtn_ConsultasLayout = new javax.swing.GroupLayout(JBtn_Consultas);
        JBtn_Consultas.setLayout(JBtn_ConsultasLayout);
        JBtn_ConsultasLayout.setHorizontalGroup(
            JBtn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_ConsultasLayout.setVerticalGroup(
            JBtn_ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BtnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_MenuPrincipal.add(JBtn_Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 270, 50));

        JLb_MarcaDeAgua.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JLb_MarcaDeAgua.setText("Made by: Calderoni, Figún & Politti");
        JPan_MenuPrincipal.add(JLb_MarcaDeAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, 20));

        JPan_Contenedor.add(JPan_MenuPrincipal, "card8");

        JPan_Altas.setBackground(new java.awt.Color(255, 255, 255));
        JPan_Altas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_AltaObjeto.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_AltaObjeto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_AltaObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltaObjetoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltaObjetoMouseExited(evt);
            }
        });

        JLb_AltaObjeto.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_AltaObjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_AltaObjeto.setText("ALTA OBJETO");
        JLb_AltaObjeto.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltaObjetoLayout = new javax.swing.GroupLayout(JBtn_AltaObjeto);
        JBtn_AltaObjeto.setLayout(JBtn_AltaObjetoLayout);
        JBtn_AltaObjetoLayout.setHorizontalGroup(
            JBtn_AltaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltaObjetoLayout.setVerticalGroup(
            JBtn_AltaObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Altas.add(JBtn_AltaObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 270, 50));

        JBtn_AltaPersona.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_AltaPersona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_AltaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltaPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltaPersonaMouseExited(evt);
            }
        });

        JLb_AltaPersona.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_AltaPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_AltaPersona.setText("ALTA PERSONA");
        JLb_AltaPersona.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltaPersonaLayout = new javax.swing.GroupLayout(JBtn_AltaPersona);
        JBtn_AltaPersona.setLayout(JBtn_AltaPersonaLayout);
        JBtn_AltaPersonaLayout.setHorizontalGroup(
            JBtn_AltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltaPersonaLayout.setVerticalGroup(
            JBtn_AltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Altas.add(JBtn_AltaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 270, 50));

        JBtn_AltaSitio.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_AltaSitio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_AltaSitio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltaSitioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltaSitioMouseExited(evt);
            }
        });

        JLb_AltaSitio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_AltaSitio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_AltaSitio.setText("ALTA SITIO");
        JLb_AltaSitio.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltaSitioLayout = new javax.swing.GroupLayout(JBtn_AltaSitio);
        JBtn_AltaSitio.setLayout(JBtn_AltaSitioLayout);
        JBtn_AltaSitioLayout.setHorizontalGroup(
            JBtn_AltaSitioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaSitio, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltaSitioLayout.setVerticalGroup(
            JBtn_AltaSitioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaSitio, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Altas.add(JBtn_AltaSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 50));

        JBtn_AltaCuadricula.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_AltaCuadricula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_AltaCuadricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltaCuadriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltaCuadriculaMouseExited(evt);
            }
        });

        JLb_AltaCuadricula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_AltaCuadricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_AltaCuadricula.setText("ALTA CUADRICULA");
        JLb_AltaCuadricula.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltaCuadriculaLayout = new javax.swing.GroupLayout(JBtn_AltaCuadricula);
        JBtn_AltaCuadricula.setLayout(JBtn_AltaCuadriculaLayout);
        JBtn_AltaCuadriculaLayout.setHorizontalGroup(
            JBtn_AltaCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltaCuadriculaLayout.setVerticalGroup(
            JBtn_AltaCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Altas.add(JBtn_AltaCuadricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 270, 50));

        JBtn_AltaCaja.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_AltaCaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_AltaCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_AltaCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_AltaCajaMouseExited(evt);
            }
        });

        JLb_AltaCaja.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_AltaCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_AltaCaja.setText("ALTA CAJA");
        JLb_AltaCaja.setFocusable(false);

        javax.swing.GroupLayout JBtn_AltaCajaLayout = new javax.swing.GroupLayout(JBtn_AltaCaja);
        JBtn_AltaCaja.setLayout(JBtn_AltaCajaLayout);
        JBtn_AltaCajaLayout.setHorizontalGroup(
            JBtn_AltaCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_AltaCajaLayout.setVerticalGroup(
            JBtn_AltaCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_AltaCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Altas.add(JBtn_AltaCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 270, 50));

        JPan_Contenedor.add(JPan_Altas, "card3");

        JPan_AltaObjeto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLb_AltaObj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JLb_AltaObj.setText("Alta de Objetos");
        JPan_AltaObjeto.add(JLb_AltaObj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 151, 32));

        jLabel1.setText("Alto");
        JPan_AltaObjeto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, -1));

        JTF_ACodObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ACodObjActionPerformed(evt);
            }
        });
        JPan_AltaObjeto.add(JTF_ACodObj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JPan_AltaObjeto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 30));

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        JPan_AltaObjeto.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, 30));

        jPanel8.setBackground(new java.awt.Color(153, 153, 0));

        jPanel9.setBackground(new java.awt.Color(153, 153, 0));

        jPanel10.setBackground(new java.awt.Color(153, 153, 0));

        jPanel11.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JPan_AltaObjeto.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 30));

        jLabel2.setText("Nombre ");
        JPan_AltaObjeto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, -1));

        JTF_ANombObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ANombObjActionPerformed(evt);
            }
        });
        JPan_AltaObjeto.add(JTF_ANombObj, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        jPanel12.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        JPan_AltaObjeto.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 220, -1));

        jLabel3.setText("Tipo de Extracción");
        JPan_AltaObjeto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 170, -1));

        JTF_ATipExtObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ATipExtObjActionPerformed(evt);
            }
        });
        JPan_AltaObjeto.add(JTF_ATipExtObj, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 170, -1));
        JPan_AltaObjeto.add(jSpin_AAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        jLabel4.setText("Código ");
        JPan_AltaObjeto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

        jLabel5.setText("Largo");
        JPan_AltaObjeto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, -1));
        JPan_AltaObjeto.add(jSpin_ALargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, -1));

        jLabel6.setText("Espesor");
        JPan_AltaObjeto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 170, -1));
        JPan_AltaObjeto.add(JSpin_AEspesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 170, -1));

        jLabel7.setText("Cantidad");
        JPan_AltaObjeto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, -1));
        JPan_AltaObjeto.add(jSpin_ACant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));
        JPan_AltaObjeto.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 180, -1));

        JPan_Contenedor.add(JPan_AltaObjeto, "card7");

        javax.swing.GroupLayout JPan_AltaPersonaLayout = new javax.swing.GroupLayout(JPan_AltaPersona);
        JPan_AltaPersona.setLayout(JPan_AltaPersonaLayout);
        JPan_AltaPersonaLayout.setHorizontalGroup(
            JPan_AltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPan_AltaPersonaLayout.setVerticalGroup(
            JPan_AltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPan_Contenedor.add(JPan_AltaPersona, "card8");

        javax.swing.GroupLayout JPan_AltaSitioLayout = new javax.swing.GroupLayout(JPan_AltaSitio);
        JPan_AltaSitio.setLayout(JPan_AltaSitioLayout);
        JPan_AltaSitioLayout.setHorizontalGroup(
            JPan_AltaSitioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPan_AltaSitioLayout.setVerticalGroup(
            JPan_AltaSitioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPan_Contenedor.add(JPan_AltaSitio, "card9");

        javax.swing.GroupLayout JPan_AltaCuadriculaLayout = new javax.swing.GroupLayout(JPan_AltaCuadricula);
        JPan_AltaCuadricula.setLayout(JPan_AltaCuadriculaLayout);
        JPan_AltaCuadriculaLayout.setHorizontalGroup(
            JPan_AltaCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPan_AltaCuadriculaLayout.setVerticalGroup(
            JPan_AltaCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPan_Contenedor.add(JPan_AltaCuadricula, "card10");

        javax.swing.GroupLayout JPan_AltaCajaLayout = new javax.swing.GroupLayout(JPan_AltaCaja);
        JPan_AltaCaja.setLayout(JPan_AltaCajaLayout);
        JPan_AltaCajaLayout.setHorizontalGroup(
            JPan_AltaCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPan_AltaCajaLayout.setVerticalGroup(
            JPan_AltaCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPan_Contenedor.add(JPan_AltaCaja, "card11");

        JPan_Listas.setBackground(new java.awt.Color(255, 255, 255));
        JPan_Listas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTable_ObjetosGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTable_ObjetosGeneral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JSP_ObjetosGeneral.setViewportView(JTable_ObjetosGeneral);

        JTbpan_General.addTab("Objetos", JSP_ObjetosGeneral);

        JTable_PersonasGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_PersonasGeneral.setViewportView(JTable_PersonasGeneral);

        JTbpan_General.addTab("Personas", JSP_PersonasGeneral);

        JTable_SitiosGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_SitiosGeneral.setViewportView(JTable_SitiosGeneral);

        JTbpan_General.addTab("Sitios", JSP_SitiosGeneral);

        JTable_CuadriculasGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_CuadriculasGeneral.setViewportView(JTable_CuadriculasGeneral);

        JTbpan_General.addTab("Cuadriculas", JSP_CuadriculasGeneral);

        JTable_CajasGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_CajasGeneral.setViewportView(JTable_CajasGeneral);

        JTbpan_General.addTab("Cajas", JSP_CajasGeneral);

        JPan_Listas.add(JTbpan_General, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 530, 330));

        JPan_Contenedor.add(JPan_Listas, "card4");

        JPan_Consultas.setBackground(new java.awt.Color(255, 255, 255));
        JPan_Consultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCB_Consultas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JCB_Consultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una consulta...", "Obtener objetos dentro de una caja", "Mostrar objetos encontrados en un período de tiempo", "Mostrar cantidad de objetos encontrados por su tipo", "Resumen de cantidades cargadas en el sistema", "Mostrar cantidad de hallazgos de cada arqueólogo", "Listar código y lugar de las cajas vacías", "Obtener el máximo, mínimo y promedio del peso de los objetos", "Obtener el peso de cada caja" }));
        JCB_Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_ConsultasActionPerformed(evt);
            }
        });
        JPan_Consultas.add(JCB_Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 440, 30));

        JBtn_BuscarConsulta.setBackground(new java.awt.Color(27, 64, 142));
        JBtn_BuscarConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBtn_BuscarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_BuscarConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_BuscarConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_BuscarConsultaMouseExited(evt);
            }
        });

        JLb_BuscarConsulta.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        JLb_BuscarConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLb_BuscarConsulta.setText("BUSCAR CONSULTA");
        JLb_BuscarConsulta.setFocusable(false);

        javax.swing.GroupLayout JBtn_BuscarConsultaLayout = new javax.swing.GroupLayout(JBtn_BuscarConsulta);
        JBtn_BuscarConsulta.setLayout(JBtn_BuscarConsultaLayout);
        JBtn_BuscarConsultaLayout.setHorizontalGroup(
            JBtn_BuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BuscarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        JBtn_BuscarConsultaLayout.setVerticalGroup(
            JBtn_BuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLb_BuscarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        JPan_Consultas.add(JBtn_BuscarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 270, 50));

        JPan_Contenedor.add(JPan_Consultas, "card5");

        getContentPane().add(JPan_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_ConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ConsultasMouseExited
        JBtn_Consultas.setBackground(new Color(27,64,142));
    }//GEN-LAST:event_JBtn_ConsultasMouseExited

    private void JBtn_ConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ConsultasMouseEntered
        JBtn_Consultas.setBackground(new Color(51,189,238));
    }//GEN-LAST:event_JBtn_ConsultasMouseEntered

    private void JBtn_ListasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ListasMouseExited
        JBtn_Listas.setBackground(new Color(27,64,142));
    }//GEN-LAST:event_JBtn_ListasMouseExited

    private void JBtn_ListasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ListasMouseEntered
        JBtn_Listas.setBackground(new Color(51,189,238));
    }//GEN-LAST:event_JBtn_ListasMouseEntered

    private void JBtn_AltasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltasMouseExited
        JBtn_Altas.setBackground(new Color(27,64,142));
    }//GEN-LAST:event_JBtn_AltasMouseExited

    private void JBtn_AltasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltasMouseEntered
        JBtn_Altas.setBackground(new Color(51,189,238));
    }//GEN-LAST:event_JBtn_AltasMouseEntered

    private void JBtn_AltasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltasMouseClicked
        JPan_Contenedor.removeAll();
        JPan_Contenedor.add(JPan_Altas);
        JPan_Contenedor.repaint();
        JPan_Contenedor.revalidate();
    }//GEN-LAST:event_JBtn_AltasMouseClicked

    private void JBtn_AltaObjetoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaObjetoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaObjetoMouseEntered

    private void JBtn_AltaObjetoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaObjetoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaObjetoMouseExited

    private void JBtn_AltaPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaPersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaPersonaMouseEntered

    private void JBtn_AltaPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaPersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaPersonaMouseExited

    private void JBtn_AltaSitioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaSitioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaSitioMouseEntered

    private void JBtn_AltaSitioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaSitioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaSitioMouseExited

    private void JBtn_AltaCuadriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaCuadriculaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaCuadriculaMouseEntered

    private void JBtn_AltaCuadriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaCuadriculaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaCuadriculaMouseExited

    private void JBtn_AltaCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaCajaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaCajaMouseEntered

    private void JBtn_AltaCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_AltaCajaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_AltaCajaMouseExited

    private void JBtn_ListasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ListasMouseClicked
        JPan_Contenedor.removeAll();
        JPan_Contenedor.add(JPan_Listas);
        JPan_Contenedor.repaint();
        JPan_Contenedor.revalidate();
    }//GEN-LAST:event_JBtn_ListasMouseClicked

    private void JBtn_ConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ConsultasMouseClicked
        JPan_Contenedor.removeAll();
        JPan_Contenedor.add(JPan_Consultas);
        JPan_Contenedor.repaint();
        JPan_Contenedor.revalidate();
    }//GEN-LAST:event_JBtn_ConsultasMouseClicked

    private void JBtn_BuscarConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BuscarConsultaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_BuscarConsultaMouseEntered

    private void JBtn_BuscarConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BuscarConsultaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_BuscarConsultaMouseExited

    private void JCB_ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_ConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_ConsultasActionPerformed

    private void JBtn_BuscarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BuscarConsultaMouseClicked
        String itemSeleccionado = new String();
        itemSeleccionado = (String) JCB_Consultas.getSelectedItem();
        
        switch (itemSeleccionado){
            case ("Obtener objetos dentro de una caja"):
                break;
            case ("Mostrar objetos encontrados en un período de tiempo"):
                break;
            case ("Mostrar cantidad de objetos encontrados por su tipo"):
                break;
            case ("Resumen de cantidades cargadas en el sistema"):
                break;
            case ("Mostrar cantidad de hallazgos de cada arqueólogo"):
                break;
            case ("Listar código y lugar de las cajas vacías"):
                break;
            case ("Obtener el máximo, mínimo y promedio del peso de los objetos"):
                break;
            case ("Obtener el peso de cada caja"):
                break;
            default:
                JOptionPane.showMessageDialog(null,"Debe seleccionar una consulta", "Error, ninguna consulta seleccionada", JOptionPane.INFORMATION_MESSAGE);
                break;
        }

    }//GEN-LAST:event_JBtn_BuscarConsultaMouseClicked

    private void Jlb_LogoBlancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlb_LogoBlancoMouseEntered
        Jlb_LogoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoColorRedimensionado.png")));
    }//GEN-LAST:event_Jlb_LogoBlancoMouseEntered

    private void Jlb_LogoBlancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlb_LogoBlancoMouseExited
        Jlb_LogoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBlancoRedimensionado.png")));
    }//GEN-LAST:event_Jlb_LogoBlancoMouseExited

    private void Jlb_LogoBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlb_LogoBlancoMouseClicked
        JPan_Contenedor.removeAll();
        JPan_Contenedor.add(JPan_MenuPrincipal);
        JPan_Contenedor.repaint();
        JPan_Contenedor.revalidate();
    }//GEN-LAST:event_Jlb_LogoBlancoMouseClicked

    private void JTF_ACodObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ACodObjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ACodObjActionPerformed

    private void JTF_ANombObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ANombObjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ANombObjActionPerformed

    private void JTF_ATipExtObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ATipExtObjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ATipExtObjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArqueologiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArqueologiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArqueologiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArqueologiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ArqueologiaFrame().setVisible(true);
                } catch (SQLException ex){
                    Logger.getLogger(ArqueologiaFrame.class.getName()).log(Level.SEVERE, null, ex);
               
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JBtn_AltaCaja;
    private javax.swing.JPanel JBtn_AltaCuadricula;
    private javax.swing.JPanel JBtn_AltaObjeto;
    private javax.swing.JPanel JBtn_AltaPersona;
    private javax.swing.JPanel JBtn_AltaSitio;
    private javax.swing.JPanel JBtn_Altas;
    private javax.swing.JPanel JBtn_BuscarConsulta;
    private javax.swing.JPanel JBtn_Consultas;
    private javax.swing.JPanel JBtn_Listas;
    private javax.swing.JComboBox<String> JCB_Consultas;
    private javax.swing.JLabel JLb_AltaCaja;
    private javax.swing.JLabel JLb_AltaCuadricula;
    private javax.swing.JLabel JLb_AltaObj;
    private javax.swing.JLabel JLb_AltaObjeto;
    private javax.swing.JLabel JLb_AltaPersona;
    private javax.swing.JLabel JLb_AltaSitio;
    private javax.swing.JLabel JLb_BtnAltas;
    private javax.swing.JLabel JLb_BtnConsultas;
    private javax.swing.JLabel JLb_BtnListas;
    private javax.swing.JLabel JLb_BuscarConsulta;
    private javax.swing.JLabel JLb_ImagenIzquierda;
    private javax.swing.JLabel JLb_MarcaDeAgua;
    private javax.swing.JPanel JPan_AltaCaja;
    private javax.swing.JPanel JPan_AltaCuadricula;
    private javax.swing.JPanel JPan_AltaObjeto;
    private javax.swing.JPanel JPan_AltaPersona;
    private javax.swing.JPanel JPan_AltaSitio;
    private javax.swing.JPanel JPan_Altas;
    private javax.swing.JPanel JPan_Consultas;
    private javax.swing.JPanel JPan_Contenedor;
    private javax.swing.JPanel JPan_Header;
    private javax.swing.JPanel JPan_Listas;
    private javax.swing.JPanel JPan_MenuPrincipal;
    private javax.swing.JScrollPane JSP_CajasGeneral;
    private javax.swing.JScrollPane JSP_CuadriculasGeneral;
    private javax.swing.JScrollPane JSP_ObjetosGeneral;
    private javax.swing.JScrollPane JSP_PersonasGeneral;
    private javax.swing.JScrollPane JSP_SitiosGeneral;
    private javax.swing.JSpinner JSpin_AEspesor;
    private javax.swing.JTextField JTF_ACodObj;
    private javax.swing.JTextField JTF_ANombObj;
    private javax.swing.JTextField JTF_ATipExtObj;
    private javax.swing.JTable JTable_CajasGeneral;
    private javax.swing.JTable JTable_CuadriculasGeneral;
    private javax.swing.JTable JTable_ObjetosGeneral;
    private javax.swing.JTable JTable_PersonasGeneral;
    private javax.swing.JTable JTable_SitiosGeneral;
    private javax.swing.JTabbedPane JTbpan_General;
    private javax.swing.JLabel Jlb_LogoBlanco;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpin_AAlto;
    private javax.swing.JSpinner jSpin_ACant;
    private javax.swing.JSpinner jSpin_ALargo;
    // End of variables declaration//GEN-END:variables
}
